### ISSUE TITLE
[UI/Frontend] Text Sentiment Extraction

### ISSUE THREAD

**Issue by ravi-prakash1907** [thedatatribune/dyPixa#36]
A UI is required to integrate the emotion classification model based on [`go-emotions`](https://github.com/thedatatribune/dyPixa/blob/main/ml_nlp/code/go_emotions.py), which is provided in the [`ml_nlp`](https://github.com/thedatatribune/dyPixa/blob/main/ml_nlp/) directory.

**The UI should include the following components:**

1. An input field for text data.
2. A button to trigger the [`findEmotions()`](https://github.com/thedatatribune/dyPixa/blob/main/ml_nlp/code/go_emotions.py#L9) function.
3. Proper error handling for empty input.
4. Display the retrieved JSON data in the most appropriate fashion.

**Comment by Zayan-dev** [comment]
hello, I know how to create the top 3 points, could you guide me how can I contribute it, I am new to open source.

**Comment by noobCoderVP** [comment]
I would like to work on this issue, I have previously worked on frontend using Material UI and Ant design in React/Next js.

**Comment by ravi-prakash1907** [comment]
Hey @Zayan-dev and @noobCoderVP,

Thanks a lot for showing interest in joining our project! As mentioned, you can kick things off by creating the basic UI components as described in the issue.

@Zayan-dev, we're really leaning towards a Django or Flask-based UI to make it super easy to connect with the backend model. So, consider hooking up Next.js with the Django frontend for this task.

**Comment by ravi-prakash1907** [comment]
> hello, I know how to create the top 3 points, could you guide me how can I contribute it, I am new to open source.


@Zayan-dev, it would be beneficial to concentrate on designing a responsive UI that can be integrated with Django. You can start by creating some initial web pages using HTML and Bootstrap, which can be further improved with the assistance of fellow contributors.

For a step-by-step guide to getting started with your contribution, please refer to [`CONTRIBUTING.md`](https://github.com/thedatatribune/dyPixa/blob/main/CONTRIBUTING.md).

**Comment by noobCoderVP** [comment]
I have worked on projects using django, I think it will be best to have django as a backend and having APIs which will run the ML algorithms and return the response. I think we should be creating frontend separately in nextjs

**Comment by ravi-prakash1907** [comment]
> I have worked on projects using django, I think it will be best to have django as a backend and having APIs which will run the ML algorithms and return the response. I think we should be creating frontend separately in nextjs

Great! You should ahead with the same approach and make sure to populate the `requirement.txt`, as well. For further discussion, you may join the [**discord server of dyPixa**](https://discord.gg/b9mVngKsJS).

**Comment by noobCoderVP** [comment]
I will use pipenv as a package manager, it is like npm for python, It adds the requirements and have the same operational functions as in npm. I will document that for use.

**Comment by noobCoderVP** [comment]
sorry for the latency, I was having my mid semester exams last week, I will complete the required features soon. Please let me know if there is any new requirement
