### ISSUE TITLE
[Dataset] Color Extraction using Python

### ISSUE THREAD

**Issue by ravi-prakash1907** [thedatatribune/dyPixa#40]
### **Description:** 📝 

We need a simple Python program to extract dominant colors from an input image (provided as a file path) and present them in hex format (e.g., white = #FFFFFF).

### **Key Focus Areas:** 🗝️🛠️

1. The program should support various image file formats (e.g., jpg, png, bmp).
2. Instead of extracting all colors, it should identify and report the top colors based on their frequency in the image.
3. In the code, please include clear and meaningful comments to enhance comprehension.

---

**Note:** 📌 _Solving this issue will contribute to the advancement of #6._

**Comment by AmithBino** [comment]
i will set the program
which folder i need to add the program

**Comment by ravi-prakash1907** [comment]
> i will set the program which folder i need to add the program

@AmithBino, place the code  [here](https://github.com/thedatatribune/dyPixa/tree/main/dataset/ImageData/code) in the sub-directory of `dataset`.

**Comment by RajaVardhan-coder** [comment]
@AmithBino how this program should work like from where it should take input image and where it should show the output

**Comment by RajaVardhan-coder** [comment]
hey i am ready with the program can you please assign it to me

**Comment by ravi-prakash1907** [comment]
> @ravi-prakash1907 hey i am ready with the program can you please assign it to me

Assigned!

**Comment by thevectorguy** [comment]
I have added a program that will prompt the user to provide the image file and output the dominant colors

**Comment by AmithBino** [comment]
Am i assigned ?

**Comment by Harinichalla20** [comment]
hey hi!
assign me this i want to do this.

**Comment by ravi-prakash1907** [comment]
> I have added a program that will prompt the user to provide the image file and output the dominant colors

Hey @thevectorguy, it seems like there is a little fix needed in your code. Do make the appropriate change as soon as possible and raise the pull request. We encourage you to join the discord server of dyPixa (link on project website / README)for further discussion.

**Comment by ravi-prakash1907** [comment]
> Hey, ravi what should i do? did u assign any works for me?

Hi @rahulrajpv, great to find you here. I believe that you should check the issue #18 and #27. You may opt to work accordingly. 🤞🤞

**Comment by ravi-prakash1907** [comment]
> hey hi! assign me this i want to do this.

Thanks for showing interest @Harinichalla20. As the task has already been assigned to enough people; I would recommend you to look into some other open and unaddressed issues like #48.
