### ISSUE TITLE
[Maintenance] Update `requirements.txt`

### ISSUE THREAD

**Issue by ravi-prakash1907** [thedatatribune/dyPixa#48]
### Description 🛠️ 

It's time to ensure our project's dependencies are up-to-date. Let's update the [`requirements.txt`](https://github.com/thedatatribune/dyPixa/blob/main/requirements.txt) file to keep our codebase fresh and reliable. Your contribution to this essential maintenance task is greatly appreciated! 🚀  

---  

**Note:** _Do ensure that you take into account the requirements of all available Python code, which can be found in the `code/` directory across various subdirectories._

**Comment by NawinKumarSharma** [comment]
i am working on this

**Comment by NawinKumarSharma** [comment]
hey @ravi-prakash1907, I have updated all the project's dependencies. Please review and merge my PR #50
