### ISSUE TITLE
[Dataset] Contribute Emotion Dataset for Color Generation 🌈

### ISSUE THREAD

**Issue by ravi-prakash1907** [thedatatribune/dyPixa#58]
### Description 🌈🎨

**Our Quest:** Let's supercharge dyPixa's creative potential! We're on a mission to build a vibrant dataset that connects emotions to colors, and we need your help to make it happen. 🚀

#### What's Needed? 📸🎨

1. **Emotional Imagery**: We're looking for images or thumbnails that express each of the **28** unique emotions. These visuals will breathe life into our dataset.

2. **Color Splash**: For each emotion, we want to collect a colorful array of at least **5** hues. These will be the building blocks of our dynamic color palettes.

#### Your Creative Input! 🎨💡

1. Shades of Emotion: Remember, there's a world of color sets that can convey the same emotion, so feel free to explore the possibilities.

2. Organized Magic: Treat each color set that aligns with a specific emotion as a distinct data entry.

3. Effortless Extraction: To make your contribution smoother, you can use [this handy script](https://github.com/ravi-prakash1907/dyPixa/blob/main/dataset/ImageData/code/ColorExtraction.py) by @thevectorguy to automatically fetch colors from your provided images or thumbnails.

**Let's Paint the World with Emotions!**

By contributing to this dataset, you're not only adding color to dyPixa's palette but also unleashing a world of creative emotions. Join us in this colorful journey and be a part of the dyPixa magic! 🎨✨

Ready to dive in? Contribute to the dyPixa Emotion Dataset and let's make emotions burst with life through colors! 🚀

---  

**Note:** _Questions or need guidance? You can join dyPixa's lively community at [Discord](https://discord.gg/b9mVngKsJS) for further discussions and queries. Your contributions mean the world to us!_ 🙌

**Comment by Addy0000** [comment]
i'd like to work on it
